#!/bin/bash

SBT_BOOT_DIR=$HOME/.sbt/boot/

if [ ! -d "$SBT_BOOT_DIR" ]; then
  mkdir -p $SBT_BOOT_DIR
fi

cat /dev/null | java -Xmx1G -XX:MaxPermSize=250m -XX:+UseCompressedOops \
    -Dsbt.log.noformat=true \
    -Dbuild.configuation.name="$TEAMCITY_BUILDCONF_NAME" \
    -Dbuild.number="$BUILD_NUMBER" \
    -Dbuild.vcs.number="$BUILD_VCS_NUMBER" \
    -Dsbt.boot.directory=$SBT_BOOT_DIR \
    -Dhttp.proxyHost=devproxy.gul3.gnl\
    -Dhttp.proxyPort=3128 \
    -jar sbt-launch-0.11.3.jar "$@"

